config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#welcome'
  get '/about/', to: 'pages#about', as: "about"
  get '/courses/', to: 'pages#courses', as: "courses"
  get '/ethics/:step', to: 'courses#ethics', as: "ethics"
  get '/addpoints/:points', to: 'courses#addpoints', as: "addpoints"
  post '/ethicsm/addanswer', to: 'courses#addanswer', as: "addanswer"
  post '/exercisecompleted', to: 'courses#exercisecompleted', as: "exercisecompleted"

end

app/models/ethic.rb
class Ethic < ApplicationRecord
  belongs_to :user
  store_accessor :answers
  store_accessor :exercises
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  #before_action :authenticate_user!
  before_action :signupandsignin

  def ethics

    @request = request.format

    @ethiccssclass = "jumbotron text-justify yellowish mt-3"

    @step = 0
    if params[:step] == nil
      @step = 0
    else
      @step = params[:step].to_i
    end
    print "step"
    print @step

    @order = [
        "introduction",
        "ethicaltheories",
        "kintro",
        "dintro",
        "dorkintro",
        "dork",
        "tintro",
        "memory",
        "whichisright",
        "dcases",
        "kinstrument",
        "tformal",
        "dwp",
        "utgf",
        "prot",
        "konk",
        "kond",
        "kont"
    ]

    @dconflicts = [
        "Die Pflicht, ausgeliehene Waffen zurückzugeben.",
        "Die Pflicht, keine Waffen auszuleihen.",
        "Die Pflicht, einem Wahnsinnigen keine Waffen zu geben",
        "Die Pflicht, Wahnsinnigen die Waffen wegzunehmen."
    ]

    @kutgf = [
        "Die Frau hat ihre Liebe nur vorgespielt. Selbst wenn wir für 5 Monate sehr glücklich waren, war es falsch von ihr, uns die Liebe vorzuspielen.",
        "Nur wahre Liebe macht einen glücklich",
        "Dieses Gedankenexperiment will zeigen, dass ",
        "Die Pflicht, Wahnsinnigen die Waffen wegzunehmen."
    ]

    @ethicaltheories = [
        "Deontologie",
        "Konsequentialismus",
        "Tugendethik"
    ]

    @dproblems = [
        "Deontologische Ethiken sind zu kompliziert, um befolgt zu werden.",
        "In gewissen Situationen kann man sich entscheiden wie man will, man macht, deontologisch gesehen, immer etwas falsch.",
        "Gewisse Handlungen, die deontologisch gut sind, führen möglicherweise zu Handlungen, die deontologisch schlecht sind.",
        "d"
    ]

    @kproblems = [
        "Der Konsequentialismus hat zu wenige Anhänger, um ernst genommen zu werden.",
        "Der Konsequentialismus behauptet, dass wir immer lügen und stehlen sollen.",
        "Der Konsequentialismus hat zur Folge, dass wir",
        "Der Konsequentialismus zieht Absichten und Intentionen nicht in Erwägung.",
        "Da die Willensfreiheit eine Illusion ist, kann man sich gar nicht für eine Handlung entscheiden.",
        "Früher oder später hat jede Handlung gute Folgen, deshalb spielt es keine Rolle, wie man sich entscheidet.",
        "In gewissen Situationen verlangt der Konsequentialismus, dass wir lügen, stehlen oder morden sollen.",
        "Der Konsequentialismus verlangt, dass wir vor jeder Entscheidung zu einer Wahrsagerin gehen.",
        "Der Konsequentialismus impliziert, dass jede Ursache eine Wirkung haben muss."
    ]

    @currentstep = @order[@step]
    print "currentstep"
    print @currentstep

    @deontvsutil = [
        ["Statt seinem reichen Freund wie versprochen das Geld zurückzugeben, spendet Stefan es an bedürftige Menschen.","ut", "Stefan versucht bedürftigen Menschen zu helfen und bricht dabei ein Versprechen. Er handelt utilitaristisch."],
        ["Lorenz verarztet einen verwundeten, feindlichen Soldaten.", "deon", "Da der Soldat Lorenz feindlich gesinnt ist, wäre es aus der Sicht von Lorenz besser, den feindlichen Soldaten zu töten, statt zu verarzten. Doch Lorenz scheint zu denken, dass es intrinsisch schlecht ist, einem verwundeten Menschen nicht zu helfen."],
        ["Fabian weigert sich, einen Terrorist zu foltern, um die von ihm versteckte Bombe zu finden.", "deon", "Eine Bombe könnte viele Menschen töten und verletzen. Ein Utilitarist würde auf die Folgen der Handlung schauen und sagen, dass durch die Folter weniger Menschen leiden müssten, als wenn nicht gefoltert wurde."],
        ["Lara zündet ein Haus an, um die Behörden auf die mangelhafte Feuerwehr aufmerksam zu machen.", "ut", "Laura erhofft sich durch ihre gefährliche Tat, dass die Behörden mehr in die Feuerwehr investieren. Dabei schaut sie auf die Folgen, nicht auf die Tat selbst."],
        ["Viele Menschen sind krank geworden. Obwohl Nadja weiss, dass ihre Medikamente nichts nützen, erzählt sie den Menschen, dass ihre Medikamente ihnen helfen würden. Sie hofft auf den Placebo-Effekt.", "ut", "Nadja lügt, in der Hoffnung gute Folgen hervorzurufen. Sie schaut auf die Folgen, nicht auf die Handlung selbst."]
    ]

    @whatareyou = [
        ["Würdest du einen Menschen umbringen, um 5 Menschen das Leben zu retten?", "Ja, ich würde dafür einen Menschen umbringen.", "Nein, ich würde dafür keinen Menschen umbringen.",[0,1]],
        ["Würdest du lügen, um einen Streit zwischen deinen Freunden zu vermeiden?", "Ja, ich würde dafür lügen.", "Nein, ich würde meinen Freunden die Wahrheit sagen.",[0,1]],
        ["Du hast 200 Franken von einem reichen Freund geliehen. Er ist sehr vergesslich. Er hat bereits vergessen, dass er dir 200 Franken geliehen hat. Würdest du ihm das Geld wie versprochen zurückgeben oder würdest du es für einen guten Zweck spenden?", "Ich würde das Geld für einen guten Zweck spenden.", "Ich würde das Geld wie versprochen zurückgeben.",[0,1]],
        ["Du kennst einen Politiker, der korrupt ist. Leider hast du nicht genügend Beweise, um ihn auf normalen Wegen hinters Licht zu führen. Würdest du einen Richter bestechen, so dass der korrupte Politiker dennoch eingesperrt wird?", "Ja, ich würde dafür den Richter bestechen.", "Nein, ich würde dafür keinen Richter bestechen.", [0,1]],
        ["Du bist Arzt. Du hast einen kranken Patienten und du weisst, dass keine deiner Medikamente ihm helfen können. Würdest du dem Patienten ein Placebo verabreichen und ihm sagen, dass ihm dieses Medikament helfen kann?", "Ja, ich würde dem Patienten ein Placebo geben.", "Nein, ich würde dem Patienten sagen, dass ich keine Medikamente für ihn habe.", [0,1]],
        ["Ein Terrorist hat eine Bombe in der Stadt versteckt, die Tausenden von Menschen das Leben kosten wird. Würdest du den Terroristen foltern, um den Ort der Bombe herauszufinden?", "Ja, ich würde den Terroristen foltern.", "Nein, ich würde den Terroristen nicht foltern.", [0,1]],
        ["Die örtliche Feuerwehr ist seit Jahren unterbezahlt und leidet an Personalmangel. Die Behörden weigern sich vehement, in die Feuerwehr zu investieren. Würdest du ein unbewohntes Haus anzünden, um die Behörden zum Umdenken zu zwingen?", "Ja, ich würde deswegen ein Haus anzünden.", "Nein, ich würde deswegen kein Haus anzünden.", [0,1]],
        ["Du bist Chirurg und ein Experte für Transplantationschirurgie. Du hast 4 Patienten, die dringend neue Organe benötigen. Zufälligerweise sitzt eine Person im Wartesaal,
          dessen Organe allen 4 Patienten das Leben retten könnten. Würdest du diese Person im Wartesaal für die anderen 4 Patienten opfern?", "Ja, ich würde diese Person für die anderen 4 opfern.", "Nein, ich würde diese Person nicht opfern.", [0,1]],
        ["Terroristen haben eine Geisel genommen und fordern Lösegeld. Die fordernden Terroristen sind bekannt dafür, dass sie ihr Wort halten und die Geisseln nach Erhalt des Lösegelds freilassen. Würdest du mit diesen Terroristen verhandeln und das Lösegeld zahlen?", "Ja, ich würde mit den Terroristen verhandeln.", "Nein, ich würde nicht mit den Terroristen verhandeln.", [0,1]],
    ]

    @memory = [
        ["Ob eine Handlung gut oder schlecht ist, hängt von den Folgen ab, die eine Handlung nach sich zieht.", 1],
        ["Konsequentialismus", 1],
        ["Ob eine Handlung gut oder schlecht ist, hängt von der Handlung selbst ab.", 2],
        ["Deontologie", 2],
        ["Eine Handlung ist gut, wenn sie viel Glück produziert und schlecht, wenn sie viel Leid verursacht.", 3],
        ["Utilitarismus", 3],
        ["Klugheit, Weisheit, Gerechtigkeit, Tapferkeit, Mässigung sind vorzügliche Eigenschaften eines Menschen.", 4],
        ["Tugende", 4],
        ["Was du nicht willst, dass man dir tu, das füg auch keinem andern zu.", 5],
        ["Goldene Regel", 5],
        ["Tugendethik", 6],
        ["Ob eine Handlung gut oder schlecht ist, hängt von der dahinterstehenden Motivation ab.", 6]
    ]

    @memory.shuffle!

    respond_to do |format|
      format.html
      format.js { render 'courses/ethics/fader.js.erb' }
    end
  end

  def addpoints
    @points = params[:points]

    current_user.points = current_user.points + @points.to_i
    current_user.save

    @points = current_user.points

    render 'addpoints.js.erb'

  end

  def addanswer
    @questionnumber = params[:questionnumber]
    @answer = params[:answer]

    e = current_user.ethic

    if @questionnumber.to_i == 9
      e.update(dork: @answer)
      rearrangeorder
    else
      e.answers[@questionnumber] = @answer
      if @answer.downcase.include?("ja")
        e.konsanswers[@questionnumber] = @answer
      else
        e.deonanswers[@questionnumber] = @answer
      end
    end

    e.save

    if @questionnumber.to_i == 9
      e.update(dork: @answer)
    end

    print e.answers

    head :ok
  end

  def exercisecompleted
    model = params[:model]
    exercise = params[:exercise]
    state = params[:state]
    @points = params[:points]

    usermodel = model.singularize.classify.constantize.find_by_user_id(current_user.id)

    currentprogress = usermodel.progress

    usermodel.update(progress: currentprogress + 10)

    if usermodel.exercises[exercise] == "completed"
      print "NOTHING!!!"
       head :ok
    else
      print usermodel.exercises[exercise]

      usermodel.exercises[exercise] = state
      print usermodel.exercises[exercise]
      usermodel.save

      print usermodel.exercises

      current_user.points = current_user.points + @points.to_i
      current_user.save

      @points = current_user.points

      render 'addpoints.js.erb'
    end
  end

  def signupandsignin
    print "jesus"
    print current_user.nil?

    if current_user.nil?
      randomname = ('a'..'z').to_a.shuffle[0,8].join
      user = User.create(
          email: randomname,
          password: 'test',
          password_confirmation: 'test'
      )

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/ethics_helper.rb
module EthicsHelper
end

app/views/courses/ethics/_backforwardbutton.html.erb
<div class="mt-5">
  <%= link_to "Zurück", ethics_path(@step - 1), class: "btn btn-primary btn-lg", remote: true  %>
  <%= link_to "Weiter", ethics_path(@step + 1), class: "btn btn-primary btn-lg", remote: true  %>
</div>

app/views/courses/ethics/_box.html.erb
<div class="jumbotron text-justify yellowish mt-3">



  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_caseintro.erb
<div class="<%=@ethiccssclass%>">
  <h1>Interessante Fälle</h1>
  <br>
  <p>
    Im Folgenden werden Fälle genannt, die Stärken und Schwächen der vorherig genannten ethischen Theorien offenlegen.
  </p>
  <p>
    Die Fälle:
  <ul>
    <li>Die "utilitaristische" Freundin</li>
    <li>Die Gestapo vor der Tür</li>
    <li>FALL FÜR TUGEND</li>
  </ul>
  </p>

  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_dcases.html.erb
<div class="<%=@ethiccssclass%>">
  <h1>Brisante Fälle</h1>
  <br>
  <p>
    Die <b>Deontologie</b> beurteilt eine Handlung nicht danach, welche Folgen sie hat,
    sondern nach <b>der Art der Handlung selbst</b>.
    Wir sollen nach der Deontologie keine Handlungen unternehmen, die <b>intrinsisch schlecht</b> sind.
    Beispiele für intrinsisch schlechte Handlungen sind <b>Lügen, Stehlen, Morden oder Verletzen</b>.
  </p>
  <p>
    Kritiker der Deontologie argumentieren, dass eine solche Ethik zu "brisanten" Fällen führt.
    Zum Beispiel: Stell dir vor, du lebst in Nazi-Deutschland und du versteckst Juden in deinem Keller.
    Eines Tages kommt die Gestapo bei dir vorbei und fragt dich, ob du Juden in deinem Haus versteckst.
    Was tun?
  </p>
  <p>
    Die Antwort der Deontologie auf diese Frage lautet: <b>Die Wahrheit sagen</b>.
    Für die Kritiker der Deontologie ist diese Antwort aus mehreren Gründen eine schlechte Antwort:
  </p>

  <ul>
    <li class="mb-2">
      Die Gestapo macht aus deontologischer Sicht viele schlechte Dinge. Die Gestapo mordet, foltert, terrorisiert und noch viel mehr.
      Macht man sich nicht zum Komplizen der Gestapo, in einem solchen Fall die Wahrheit zu sagen?
      <b>Wie kann es gut sein, sich zum Komplizen der Gestapo zu machen?</b>
    </li>
    <li class="mb-2">
      Hier scheint ein <b>Konflikt</b> zwischen zwei <b>intrinsisch guten</b> Handlungen entstanden zu sein.
      Einerseits will man die Juden vor dem Konzentrationslager retten, eine intrinsisch gute Handlung,
      andererseits will man die Wahrheit sagen, auch eine intrinsisch gute Handlung.
      Man kann aber nicht beides tun. <b>Egal wie man handelt, man macht in beiden Fällen etwas falsch.</b>
      Darf eine gute Theorie solche Konflikte erlauben?
    </li>
  </ul>
  <p>
    Manche Kritiker der Deontologie argumentieren, dass man in solchen "brisanten" Fällen die <b>Unplausibilität</b> der Deontologie erkennen kann.
    Deontologen halten dagegen und meinen, dass die eben genannten Probleme zwar ernst sind, diese aber gelöst oder behoben werden können.
  </p>
  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_dintro.html.erb
<div class="<%=@ethiccssclass%>">
  <h1>Die Deontologie</h1>
  <br>
  <p>
    Die <b>Deontologie</b> beurteilt eine Handlung nicht danach, welche Folgen sie hat,
    sondern nach <b>der Art der Handlung selbst</b>.
  </p>
  <p>
    Wenn uns jemand ein <b>Versprechen</b> gibt, dann erwarten wir, dass diese Person dieses Versprechen auch <b>hält</b>.
  </p>
  <p>
    Wenn wir uns mit jemanden <b>unterhalten</b>, dann wollen wir nicht, dass diese Person uns <b>anlügt</b>.
  </p>
  <p>
    Wenn jemand aber ein <b>Versprechen bricht</b> oder <b>lügt</b>, so die Deontologie, dann ist die Handlung schlecht,
    <b>unabhängig von den Folgen</b>, die jene Handlung nach sich zieht.
  </p>
  <p>
    Gewisse Handlungen, wie Lügen oder das Brechen von Versprechen, sind <b>schlecht an sich</b>, sie sind, wie man sagt, <b>intrinsisch schlecht</b>.
  </p>
  <p>
    Die Frage ist nun, <b>welche Handlungen intrsinsisch gut</b> und <b>welche intrinsisch schlecht</b> sind.
  </p>
  <p>
    Ein Vorschlag, wie man den <b>intrinsischen Wert</b> einer Handlung <b>bestimmen</b> kann, ist wie folgt:
  </p>

  <p class="ml-3">
    <em>Eine Handlung ist intrinsisch schlecht, <b>wenn du nicht möchtest, dass man sie bei dir macht</b>.<br><br>
    Eine Handlung ist intrinsisch gut, <b>wenn du froh wärst, dass man sie bei dir macht</b>.</em>
  </p>
  <hr class="my-4">
  <p>
    Ein Beispiel, wie man eine Handlung in der Deontologie bewertet, könnte so aussehen: <br><br>
    Ist <b>Stehlen</b> intrinsisch schlecht? Möchtest du bestohlen werden? Falls nein, dann ist Stehlen intrinsisch schlecht.<br><br>
    Ist <b>Nothilfe leisten</b> intrinsisch gut? Möchtest du im Notfall Nothilfe bekommen? Falls ja, dann ist Nothilfe leisten intrinsischt gut.
  </p>

  <p>
    Dieses Prinzip nennt man manchmal auch die <b>goldene Regel</b>: <em>„Was du nicht willst, dass man dir tu, das füg auch keinem andern zu.“</em>
  </p>


  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_dorkintro.html.erb
<div class="<%=@ethiccssclass%>">
  <h1>Ein Persönlichkeitstest!</h1>
  <br>
  <p>
    Da der <b>Konsequentialismus</b> und die <b>Deontologie</b> Handlungen unterschiedlich bewerten, liefern sie manchmal auch <b>unterschiedliche Empfehlungen</b> ab, wie man sich in bestimmten Situationen <b>verhalten soll</b>.
  </p>
  <p>
    <b>Finde heraus, nach welcher Ethik du dich richtest!</b>
  </p>
  <p>
    Auf der nächsten Seite begegnest du klassischen Fällen, in denen sich Konsequentialisten und Deontologen unterschiedlich verhalten würden.
  </p>
  <p>
    Wie würdest du dich in diesen Fällen entscheiden?
  </p>

  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_introduction.html.erb
<div class="<%=@ethiccssclass%>">
  <h1>Was ist Ethik?</h1>
  <br>
  <p>Ethik ist eine philosophische Disziplin, die sich mit der <b>Bewertung menschlichen Handelns</b> auseinandersetzt.</p>
  <p>Im Alltag beurteilen wir oft Handlungen. Wir sagen zum Beispiel, dass es gut ist, einem alten Menschen über die Strasse zu helfen, während wir Diebstahl oder Lügen als schlecht beurteilen.
  </p>
  <p>
    Doch warum ist Diebstahl schlecht? Und warum sollten wir alten Menschen über die Strasse helfen? Die Ethik versucht solche Fragen zu beantworten.
  </p>
  <p class="lead">
    <%= link_to "Mit dem Kurs anfangen", ethics_path(@step + 1), class: "btn btn-primary btn-lg", remote: true %>
  </p>
</div>

app/views/courses/ethics/_kintro.html.erb
<div class="<%=@ethiccssclass%>">

  <h1>Der Konsequentialismus</h1>
  <br>
  <p>
    Im <b>Konsequentialismus</b> werden Handlungen im Bezug auf <b>die Folgen</b> beurteilt, die eine Handlung nach sich zieht.
  </p>
  <p>
    Eine Handlung ist <b>gut</b>, wenn sie <b>gute Folgen</b> hat und eine Handlung ist <b>schlecht</b>, wenn sie <b>schlechte Folgen</b> hat.
  </p>
  <p>
    Die Frage ist nun, was man genau unter <b>guten</b> und <b>schlechten Folgen</b> verstehen soll.
  </p>
  <p>
    Der <b>Utilitarismus</b>, eine bekannte konsequentialistische Position, argumentiert, dass eine Handlung gut ist, wenn sie <b>viel Glück bringt</b> und dass
    eine Handlung schlecht ist, wenn sie <b>viel Leid produziert</b>.
  </p>
  <hr class="my-4">
  <p>
    Ein Beispiel, wie man eine Handlung im Utilitarismus bewertet, könnte so aussehen:
  </p>
  <p>
    Angenommen, wir haben zwei Handlungsoptionen. Nennen wir sie Handlung A und Handlung B.
  <ul>
    <li> Handlung A führt dazu, dass 10 Menschen glücklich werden und 2 Menschen leiden.</li>
    <li> Handlung B führt dazu, dass 2 Menschen glücklich werden und 10 Menschen leiden.</li>
  </ul>
  Nach dem Utilitarismus können wir nun die zwei Handlungen im Bezug auf die Folgen <b>vergleichen</b>.
    Verglichen zur Handlung B, werden bei Handlung A <b>mehr Menschen glücklick</b> und es müssen <b>weniger Menschen leiden</b>. Somit ist Handlung A <b>besser</b> als Handlung B.
    Dabei spielt es nach dem Utilitarismus keine Rolle, von welcher Art die Handlung A ist.
  </p>


  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>

app/views/courses/ethics/_kwp.html.erb
<div class="alert alert-info mt-3">
  <strong>Aufgabe:</strong> Im Folgenden hörst du eine Argumentation eines <b>Konsequentialisten</b>. Überlege dir, wie ein <b>Kritiker des Konsequentialismus'</b> darauf antworten könnte.
</div>

<div class="alert alert-warning mt-3">
  Ich denke,
</div>


<% i = 0 %>
<ul class="form-check">
  <% @kproblems.each do |problem| %>
      <li class="list-group-item">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" value="<%= i %>">
          <%= problem %>
        </label>

      </li>
      <% i = i + 1 %>
  <% end %>
</ul>

<div class="alert alert-danger hidden-xl-down">
  <strong>Nicht alle Antworten sind richtig!</strong> Versuche es erneut!
</div>

<div class="alert alert-success hidden-xl-down">
  <strong>Richtig!</strong> <%= link_to "Weiter", ethics_path("dintroduction"), class: "btn btn-primary btn-md" %>
</div>

<%= link_to "Weiter", ethics_path("dintroduction"), class: "btn btn-primary btn-md hidden-xl-down" %>

<button type="button" id="checkresult" class="btn btn-primary">Auswahl überprüfen</button>

<script>
    $(document).ready(function() {
        $("#checkresult").click(function(event){
            event.preventDefault();
            var result = $('input:checked').map(function(){
                return $(this).val();
            });
            var result = result.get();
            console.log(result.toString() == ["2", "3", "6"].toString());
            if(result.toString() == ["2", "3", "6"].toString()){
                $('.alert-success').removeClass('hidden-xl-down');
                $('.alert-danger').addClass('hidden-xl-down');
            } else {
                $('.alert-danger').removeClass('hidden-xl-down');
                $('.alert-success').addClass('hidden-xl-down');
            };

        });
    });
</script>

app/views/courses/ethics/_memory.html.erb
<div class="alert alert-info mt-3">
  <strong>Memory mit ethischen Begriffen: Finde die passenden Karten!</strong>
</div>

<div class="hidden-sm-up">
  Da dein Gerät einen kleinen Bildschirm hat, kannst du diese Aufgabe überspringen:
  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>
</div>

<div id="backforward" class="card hidden-xl-down">
  <div class="card-header">
    <b>Übung abgeschlossen!</b>!
  </div>
  <div class="card-block">
    <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>
  </div>
</div>

<% i = 0 %>
<div class="row">
  <% @memory.each do |card| %>
      <% i = i + 1 %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <div id="<%=i%>" value="<%=card[1]%>" class="flip my-2">

          <div class="front yellowishcard text-center cardsize p-1">

          </div>

          <div class="back yellowishcard text-center cardsize p-1">
            <%= card[0] %>
          </div>

        </div>
      </div>
  <% end %>

</div>

<script>
    $(document).ready(function() {
        var flippedcard1 = 0;
        var flippedcard2 = 0;
        var score = 0;

        $('.flip').on('click', function (){
            var currentcard = $(this).attr("id");

            console.log(flippedcard1 + " | " + flippedcard2);

            if((flippedcard1 > 0) && (flippedcard2 > 0)){
                $('#' + flippedcard1).flip(false);
                $('#' + flippedcard2).flip(false);
                flippedcard1 = 0;
                flippedcard2 = 0;

            }  else if($('#' + currentcard).children().hasClass('greenishcard')){
                console.log("nothing should happen");
            } else if((flippedcard1 > 0) && (flippedcard1 !== currentcard)) {
                $('#' + currentcard).flip('toggle');
                if ($('#' + currentcard).attr("value") === $('#' + flippedcard1).attr("value")) {

                    $('#' + currentcard).removeClass('flip');
                    $('#' + flippedcard1).removeClass('flip');

                    $('#' + currentcard).children().removeClass('yellowishcard').addClass('greenishcard');
                    $('#' + flippedcard1).children().removeClass('yellowishcard').addClass('greenishcard');

                    flippedcard1 = 0;
                    score = score + 1;

                    if(score === 6){
                        var title = 'Memory abgeschlossen!';
                        var text = 'Du hast alle Paare gefunden!';

                        resultswal(title, text, 500, "ethic", "memory", "completed");
                        $('#backforward').fadeIn("slow").removeClass("hidden-xl-down");
                    }

                } else {
                    flippedcard2 = currentcard;
                }
            } else if(flippedcard1 === currentcard){
                $('#' + currentcard).flip('toggle');
                flippedcard1 = 0;
            } else {
                $('#' + currentcard).flip('toggle');
              flippedcard1 = $(this).attr("id");
            }
        });


        $(".flip").flip({
            trigger: 'manual'
        });

    });
</script>

app/views/courses/ethics/_whichisright.html.erb
<div class="<%=@ethiccssclass%>">
  <h1>Nach welcher Theorie sollen wir uns richten?</h1>
  <br>
  <p>
    Die drei vorgestellten ethischen Theorien bewerten Handlungen unterschiedlich.
    Die Frage ist nun, welche Theorie die richtige ist.
    Die Auswahl der Theorie legt fest, was wir tun <b>sollen</b>
    und ob das was wir tun, <b>lobens-</b> oder <b>tadelnswert</b> ist.
  </p>
  <p>
    Im Folgenden werden Überlegungen vorgestellt, die jeweils
    für oder gegen eine ethische Theorie sprechen.
  </p>

  <%= render "courses/ethics/backforwardbutton", locals: {step: @step} %>

</div>