config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#welcome'
  get '/about/', to: 'pages#about', as: "about"
  get '/courses/', to: 'pages#courses', as: "courses"
  get '/ethics/:step', to: 'courses#ethics', as: "ethics"
  get '/addpoints/:points', to: 'courses#addpoints', as: "addpoints"
  post '/ethicsm/addanswer', to: 'courses#addanswer', as: "addanswer"
  post '/exercisecompleted', to: 'courses#exercisecompleted', as: "exercisecompleted"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lernspiel2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.0/sweetalert2.all.min.js" integrity="sha256-nfbZ2BnFr4dgchZRXhCi5uXTjG93NdgqiwhPSpD94T8=" crossorigin="anonymous"></script>
    <script src="jquery.ui.touch-punch.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded navbuffer">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to root_path do %>
        <div class="navbar-brand d-inline"><%= image_tag("logo.png", height: '30') %></div>
    <% end %>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
          <div class="navbar-brand">Punkte: <span class="counter"><%= current_user.points %></span></div>
      <% end %>
    </ul>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Kurse", courses_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Über uns", about_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item hidden-xl-down">
              <div class="navbar-brand"><%= current_user.email %></div>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">

    <% if notice %>
        <div class="alert alert-success mt-3" role="alert">
          <%= notice %>
        </div>
    <% end %>

    <% if alert %>
        <div class="alert alert-warning mt-3" role="alert">
          <%= alert %>
        </div>
    <% end %>

    <%= yield %>
  </div>

  <div style="margin-top: 80px;"></div>

  <div class=" text-center fixed-bottom grey-bg mt-2 p-2">

    <% if user_signed_in? %>
          <div class="navbar-brand">Punkte: <span class="counter"><%= current_user.points %></span></div>
    <% else %>
        <%= link_to root_path do %>
            <div class="navbar-brand"><%= image_tag("logo.png", height: '30') %></div>
        <% end %>
    <% end %>
  </div>

  </body>
</html>